version: 0.2

env:
  variables:
    BUCKET_NAME: "tonik-bank-sftp-uat"
    FILE_NAME: "BF_AggregatedGLTransactionExtract_2024-09-02_213228.csv"
    DATE_FOLDER: ""

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip3 install -r requirements.txt

  build:
    commands:
      - echo ${BUCKET_NAME}
      
      # Download the file from S3
      - aws s3 cp s3://${BUCKET_NAME}/finastra/GLExtract/AggregatedGLExtract/in/${FILE_NAME} .

      # Convert file to Unix format in case it has Windows line endings
      - sed -i 's/\r$//' ${FILE_NAME}

      # Use awk to update rows where both NOMINALCODE and NOMINALDESCRIPTION are missing
      - |
          awk -F, '{
            if ($1 == "" && $2 == "") {
              $1 = "4000692"
              $2 = "Off BS Loan Account"
            }
            print $0
          }' OFS=, ${FILE_NAME} > Data_check_${FILE_NAME}

      # Compare the original file and the modified file
      # We place the modified file with a '-1' suffix regardless
      - |
          filename=`echo ${FILE_NAME} | cut -d '.' -f1`
          ext=`echo ${FILE_NAME} | cut -d '.' -f2`
          mv Data_check_${FILE_NAME} "${filename}_1.${ext}"

          # Upload the modified file back to S3
          aws s3 cp "${filename}_1.${ext}" s3://${BUCKET_NAME}/finastra/GLExtract/AggregatedGLExtract/in/"${filename}_1.${ext}"

          # Update FILE_NAME to the new file name
          FILE_NAME=${filename}_1.${ext}

      # Additional build steps
      - pwd
      - ls -ltr
      - echo $DATE_FOLDER
      - python agg_GLExtract.py ${FILE_NAME} ${DATE_FOLDER}
      - aws s3 cp validation_report_AggGLExtract_${DATE_FOLDER}.txt s3://${BUCKET_NAME}/openKM/CoreAutomation-Validation-Checks/AggGLExtract/validation_report_AggGLExtract_${DATE_FOLDER}.txt
      - aws codebuild start-build --project-name 'Finastra-to-SAP-file-transformation' --environment-variables-override "[{\"name\":\"FILENAME\",\"value\":\"${FILE_NAME}\",\"type\":\"PLAINTEXT\"}]"
